name: Example GitHub Actions Workflow

on:
  workflow_dispatch:
    branches:
      - prod
      
# Defines the jobs to be run
jobs:
  build:
    # Specifies the runner environment
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
