name: Example GitHub Actions Workflow

# Defines the events under which the workflow will run
on:
 workflow_dispatch:
   inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      environment:
        description: 'Environment name'
        required: true

# Defines the jobs to be run
jobs:
  build:
    # Specifies the runner environment
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
